<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Remove="Assets\capasitor.svg" />
    <None Remove="Assets\dc_voltage_source.svg" />
    <None Remove="Assets\resistor.svg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CircuitCore\CircuitCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="SharpVectors" Version="1.8.5" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\capasitor.svg" />
    <Resource Include="Assets\dc_voltage_source.svg" />
    <Resource Include="Assets\resistor.svg" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
